spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  key: ${APP_KEY}

api:
  key: ${API_KEY}

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#===

logging:
  level:
    org.springframework.beans.factory.support: INFO
    org.springframework.context.annotation: INFO
