spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  key: ${APP_KEY}

api:
  key: ${API_KEY}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


#===

logging:
  level:
    org.springframework.beans.factory.support: INFO
    org.springframework.context.annotation: INFO

schedules:
  krx:
    listed:
      enabled: true
      cron: "*/10 * * * * MON-FRI"
      num-of-rows: 3000
      date-mode: lastWeekMonday

kis:
  base-url: https://openapi.koreainvestment.com:9443
  token-path: /oauth2/tokenP
  app-key: ${APP_KEY}
  app-secret: ${APP_SECRET}
  refresh-skew-seconds: 60
  retry:
    max-attempts: 5
    base-delay-ms: 250
    max-delay-ms: 3000
  investor:
    path: /uapi/domestic-stock/v1/quotations/inquire-investor-time-by-market
    tr_id: FHPTJ04030000
  minute-value:
    path: /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
    tr_id: FHKST03010200
  daily-minute-value:
    path: /uapi/domestic-stock/v1/quotations/inquire-time-dailychartprice
    tr_id: FHKST03010230

batch:
  investor:
    markets: KOSPI