
### POST#1
POST {{baseUrl}}/api/stock-data/aggregate30m
Content-Type: application/json

{
  "symbols": ["005930"],
  "endTime": "10:30:00",
  "lastData": "Y"
}


### POST#2
POST {{remoteUrl}}/api/stocks/search
Content-Type: application/json

{
  "symbols": ["005930"],
  "endTime": "10:30:00",
  "lastData": "Y"
}

### POST#3
POST {{baseUrl}}/api/sync/krx/investor?divCode=J&symbol=000810
