apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-server-deployment
  labels:
    app: stock-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-server-app
  template:
    metadata:
      labels:
        app: stock-server-app
    spec:
      containers:
        - name: stock-server-container
          image: docker.io/choizia/stock-server-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: stock-server-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: stock-server-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stock-server-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: stock-server-secrets
                  key: APP_KEY
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: stock-server-secrets
                  key: APP_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: stock-server-deployment
  labels: { app: stock-server-app }
spec:
  type: NodePort
  selector: { app: stock-server-app }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30020