apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
  labels:
    app: node-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server-app
  template:
    metadata:
      labels:
        app: node-server-app
    spec:
      containers:
        - name: node-server-container
          image: node-server-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: key-secret
                  key: data-api-key
            - name: TNS_ADMIN
              value: /app/wallet
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/wallet
      volumes:
        - name: wallet-volume
          hostPath:
            path: /home/opc/wallet
            type: Directory
