apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
  labels:
    app: node-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server-app
  template:
    metadata:
      labels:
        app: node-server-app
    spec:
      containers:
        - name: node-server-container
          image: node-server-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: key-secret
                  key: data-api-key
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg_host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg_port
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg_user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg_password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg_db
