# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment # 배포 이름
  labels:
    app: node-server-app # 앱 레이블 (Service와 연결에 사용)
spec:
  replicas: 1 # 실행할 Pod 개수 (테스트 환경이므로 1개로 시작)
  selector:
    matchLabels:
      app: node-server-app
  template:
    metadata:
      labels:
        app: node-server-app # Pod 레이블 (Service와 연결에 사용)
    spec:
      containers:
        - name: node-server-container # 컨테이너 이름
          image: docker.io/library/node-server-app:latest # Jenkins가 빌드할 이미지 이름
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 # 컨테이너가 노출할 포트 (Node.js 서버 포트)
          resources: # 리소스 요청 및 제한 (필요시 조정)
            requests:
              cpu: "250m" # 0.25 vCPU
              memory: "256Mi" # 256 MB
            limits:
              cpu: "500m" # 0.5 vCPU
              memory: "512Mi" # 512 MB
          env: # 환경 변수 설정
            - name: API_KEY # API 키 환경 변수
              valueFrom:
                secretKeyRef:
                  name: key-secret # Secret 이름
                  key: data-api-key # Secret
