#kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  type: NodePort
  selector:
    app: node-server-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 33000 # 외부에서 접속할 포트
